# Dotfiles Makefile (Hybrid: Stow + Manual Fallback)

DOTFILES_DIR := $(shell pwd)
STOW         := $(shell command -v stow 2> /dev/null)

# Colors
BLUE   := \033[0;34m
GREEN  := \033[0;32m
YELLOW := \033[1;33m
RED    := \033[0;31m
BOLD   := \033[1m
NC     := \033[0m

# Helpers
INFO    := @printf "$(BLUE)==>$(NC) $(BOLD)%s$(NC)\n"
SUCCESS := @printf "$(GREEN)[ok]$(NC) %s\n"
WARN    := @printf "$(YELLOW)[warn]$(NC) %s\n"

.PHONY: all install sync status update clean bash vim neovim tmux git utils fonts inputrc help uninstall

all: help

help:
	@printf "$(BOLD)Usage: make [target]$(NC)\n\n"
	@printf "Targets:\n"
	@printf "  install (or sync)  Link all dotfiles to home directory\n"
	@printf "  status             Check installation status\n"
	@printf "  update             Pull latest changes and sync\n"
	@printf "  clean (uninstall)  Remove dotfiles symlinks\n"
	@printf "\nComponents:\n"
	@printf "  bash, vim, neovim, tmux, git, utils, fonts, inputrc\n"

# Macro for linking (Manual Fallback)
define link_file
	dest=$(2); \
	if [ -L "$$dest" ]; then \
		rm "$$dest"; \
	elif [ -e "$$dest" ]; then \
		backup="$$dest.backup.$$(date +%Y%m%d_%H%M%S)"; \
		printf "$(YELLOW)[warn]$(NC) Backing up %s to %s\n" "$$dest" "$$backup"; \
		mv "$$dest" "$$backup"; \
	fi; \
	mkdir -p "$$(dirname "$$dest")"; \
	ln -sfn "$(1)" "$$dest"; \
	printf "$(GREEN)[ok]$(NC) Linked %s -> %s\n" "$(1)" "$$dest"
endef

# Macro for Stow or Fallback
define stow_or_link
	@if [ -n "$(STOW)" ]; then \
		stow --dotfiles -t $(HOME) $(1); \
		printf "$(GREEN)[stow]$(NC) %s\n" "$(1)"; \
	else \
		$(2); \
	fi
endef

install: sync

sync: bash vim neovim tmux git utils fonts inputrc

bash:
	$(INFO) "Configuring Bash..."
	$(call stow_or_link,bash,$(call link_file,$(DOTFILES_DIR)/bash/dot-dir_colors,$(HOME)/.dir_colors))
	@if grep -q "# BEGIN DOTFILES" $(HOME)/.bashrc 2>/dev/null; then \
		printf "$(GREEN)[ok]$(NC) Bash extensions already present\n"; \
	else \
		printf "\n# BEGIN DOTFILES\n# Generated by dotfiles Makefile\n[ -f \"$(DOTFILES_DIR)/bash/dot-bashrc_ext\" ] && source \"$(DOTFILES_DIR)/bash/dot-bashrc_ext\"\n# END DOTFILES\n" >> $(HOME)/.bashrc; \
		printf "$(GREEN)[ok]$(NC) Added source block to ~/.bashrc\n"; \
	fi
	@if [ ! -f $(HOME)/.bashrc.local ]; then \
		printf "# Local machine-specific overrides\n# This file is ignored by git\n" > $(HOME)/.bashrc.local; \
		printf "$(GREEN)[ok]$(NC) Created ~/.bashrc.local template\n"; \
	fi

vim:
	$(INFO) "Configuring Vim..."
	@mkdir -p $(DOTFILES_DIR)/vim/dot-vim/undo $(DOTFILES_DIR)/vim/dot-vim/backup $(DOTFILES_DIR)/vim/dot-vim/swap
	$(call stow_or_link,vim,$(call link_file,$(DOTFILES_DIR)/vim/dot-vimrc,$(HOME)/.vimrc); $(call link_file,$(DOTFILES_DIR)/vim/dot-vim,$(HOME)/.vim))

neovim:
	$(INFO) "Configuring Neovim..."
	$(call stow_or_link,nvim,$(call link_file,$(DOTFILES_DIR)/nvim/dot-config/nvim,$(HOME)/.config/nvim))

tmux:
	$(INFO) "Configuring Tmux..."
	$(call stow_or_link,tmux,$(call link_file,$(DOTFILES_DIR)/tmux/dot-tmux.conf,$(HOME)/.tmux.conf))

git:
	$(INFO) "Configuring Git..."
	$(call stow_or_link,git,$(call link_file,$(DOTFILES_DIR)/git/dot-gitignore_global,$(HOME)/.gitignore_global))
	@if [ -f $(HOME)/.gitconfig ] && ! grep -q "Git configuration template" $(HOME)/.gitconfig 2>/dev/null; then \
		printf "$(YELLOW)[warn]$(NC) ~/.gitconfig exists and isn't a dotfiles template. Skipping.\n"; \
	else \
		cp $(DOTFILES_DIR)/git/dot-gitconfig $(HOME)/.gitconfig; \
		printf "$(GREEN)[ok]$(NC) Git config installed\n"; \
	fi

utils:
	$(INFO) "Configuring Utilities..."
	$(call stow_or_link,utils,$(call link_file,$(DOTFILES_DIR)/utils/dot-bin,$(HOME)/.bin))
	@chmod +x $(DOTFILES_DIR)/utils/dot-bin/* 2>/dev/null || true

fonts:
	$(INFO) "Configuring Fonts..."
	$(call stow_or_link,fonts,$(call link_file,$(DOTFILES_DIR)/fonts/dot-local/share/fonts,$(HOME)/.local/share/fonts))
	@if command -v fc-cache >/dev/null 2>&1; then fc-cache -f; fi

inputrc:
	$(INFO) "Configuring Inputrc..."
	$(call stow_or_link,inputrc,$(call link_file,$(DOTFILES_DIR)/inputrc/dot-inputrc,$(HOME)/.inputrc))

clean: uninstall

uninstall:
	$(INFO) "Cleaning up dotfiles..."
	@if [ -n "$(STOW)" ]; then \
		stow --dotfiles -D -t $(HOME) bash vim nvim tmux git utils fonts inputrc 2>/dev/null || true; \
	else \
		for f in .dir_colors .vimrc .tmux.conf .gitignore_global .inputrc .vim .config/nvim .bin .local/share/fonts; do \
			if [ -L "$(HOME)/$$f" ]; then rm -f "$(HOME)/$$f"; fi; \
		done; \
	fi
	@sed -i '/# BEGIN DOTFILES/,/# END DOTFILES/d' $(HOME)/.bashrc 2>/dev/null || true
	@if [ -f $(HOME)/.gitconfig ] && grep -q "Git configuration template" $(HOME)/.gitconfig 2>/dev/null; then rm -f $(HOME)/.gitconfig; fi
	@printf "$(GREEN)[ok]$(NC) Cleanup complete\n"

status:
	@printf "$(BOLD)Dotfiles Status:$(NC)\n"
	@if grep -q "# BEGIN DOTFILES" $(HOME)/.bashrc 2>/dev/null; then printf "  $(GREEN)[installed]$(NC) Bash\n"; else printf "  $(RED)[missing]  $(NC) Bash\n"; fi
	@if [ -e $(HOME)/.vimrc ]; then printf "  $(GREEN)[installed]$(NC) Vim\n"; else printf "  $(RED)[missing]  $(NC) Vim\n"; fi
	@if [ -e $(HOME)/.config/nvim/init.lua ]; then printf "  $(GREEN)[installed]$(NC) Neovim\n"; else printf "  $(RED)[missing]  $(NC) Neovim\n"; fi
	@if [ -e $(HOME)/.tmux.conf ]; then printf "  $(GREEN)[installed]$(NC) Tmux\n"; else printf "  $(RED)[missing]  $(NC) Tmux\n"; fi
	@if [ -e $(HOME)/.gitignore_global ]; then printf "  $(GREEN)[installed]$(NC) Git\n"; else printf "  $(RED)[missing]  $(NC) Git\n"; fi
	@if [ -e $(HOME)/.bin/sysinfo ]; then printf "  $(GREEN)[installed]$(NC) Utils\n"; else printf "  $(RED)[missing]  $(NC) Utils\n"; fi
	@if [ -e $(HOME)/.local/share/fonts/Terminus ]; then printf "  $(GREEN)[installed]$(NC) Fonts\n"; else printf "  $(RED)[missing]  $(NC) Fonts\n"; fi
	@if [ -e $(HOME)/.inputrc ]; then printf "  $(GREEN)[installed]$(NC) Inputrc\n"; else printf "  $(RED)[missing]  $(NC) Inputrc\n"; fi

update:
	git pull
	$(MAKE) sync
