# Dotfiles Makefile

DOTFILES_DIR := $(shell pwd)
NVIM_CONF    := $(HOME)/.config/nvim
BIN_DIR      := $(HOME)/.bin
FONT_DIR     := $(HOME)/.local/share/fonts/dotfiles

# Colors
BLUE   := \033[0;34m
GREEN  := \033[0;32m
YELLOW := \033[1;33m
RED    := \033[0;31m
BOLD   := \033[1m
NC     := \033[0m

# Helpers
INFO    := @printf "$(BLUE)==>$(NC) $(BOLD)%s$(NC)\n"
SUCCESS := @printf "$(GREEN}[ok]$(NC) %s\n"
WARN    := @printf "$(YELLOW}[warn]$(NC) %s\n"

.PHONY: all install sync status update clean bash vim neovim tmux git utils fonts inputrc help uninstall

all: help

help:
	@printf "$(BOLD)Usage: make [target]$(NC)\n\n"
	@printf "Targets:\n"
	@printf "  install (or sync)  Link all dotfiles to home directory\n"
	@printf "  status             Check installation status\n"
	@printf "  update             Pull latest changes and sync\n"
	@printf "  clean (uninstall)  Remove dotfiles symlinks\n"
	@printf "\nComponents:\n"
	@printf "  bash, vim, neovim, tmux, git, utils, fonts, inputrc\n"

# Macros for linking
define link_file
	@dest=$(2); \
	if [ -L "$$dest" ]; then \
		rm "$$dest"; \
	elif [ -e "$$dest" ]; then \
		backup="$$dest.backup.$$(date +%Y%m%d_%H%M%S)"; \
		printf "$(YELLOW}[warn]$(NC) Backing up %s to %s\n" "$$dest" "$$backup"; \
		mv "$$dest" "$$backup"; \
	fi; \
	mkdir -p "$$(dirname "$$dest")"; \
	ln -sfn "$(1)" "$$dest"; \
	printf "$(GREEN}[ok]$(NC) Linked %s -> %s\n" "$(1)" "$$dest"
endef

install: sync

sync: bash vim neovim tmux git utils fonts inputrc

bash:
	$(INFO) "Configuring Bash..."
	@if [ -f "$(DOTFILES_DIR)/_dir_colors" ]; then $(call link_file,$(DOTFILES_DIR)/_dir_colors,$(HOME)/.dir_colors); fi
	@if grep -q "# BEGIN DOTFILES" $(HOME)/.bashrc 2>/dev/null; then \
		printf "$(GREEN}[ok]$(NC) Bash extensions already present\n"; \
	else \
		printf "\n# BEGIN DOTFILES\n# Generated by dotfiles Makefile\n[ -f \"$(DOTFILES_DIR)/_bashrc\" ] && source \"$(DOTFILES_DIR)/_bashrc\"\n# END DOTFILES\n" >> $(HOME)/.bashrc; \
		printf "$(GREEN}[ok]$(NC) Added source block to ~/.bashrc\n"; \
	fi
	@if [ ! -f $(HOME)/.bashrc.local ]; then \
		printf "# Local machine-specific overrides\n# This file is ignored by git\n" > $(HOME)/.bashrc.local; \
		printf "$(GREEN}[ok]$(NC) Created ~/.bashrc.local template\n"; \
	fi

vim:
	$(INFO) "Configuring Vim..."
	$(call link_file,$(DOTFILES_DIR)/_vimrc,$(HOME)/.vimrc)
	@if [ -d "$(DOTFILES_DIR)/_vim" ]; then \
		$(call link_file,$(DOTFILES_DIR)/_vim,$(HOME)/.vim); \
	fi
	@mkdir -p $(HOME)/.vim/{undo,backup,swap}
	@if [ -d "$(DOTFILES_DIR)/_config/nvim/colors" ]; then \
		$(call link_file,$(DOTFILES_DIR)/_config/nvim/colors,$(HOME)/.vim/colors); \
	fi

neovim:
	$(INFO) "Configuring Neovim..."
	$(call link_file,$(DOTFILES_DIR)/_config/nvim,$(NVIM_CONF))

tmux:
	$(INFO) "Configuring Tmux..."
	$(call link_file,$(DOTFILES_DIR)/_tmuxrc,$(HOME)/.tmux.conf)

git:
	$(INFO) "Configuring Git..."
	@if [ -f "$(DOTFILES_DIR)/_gitignore_global" ]; then \
		$(call link_file,$(DOTFILES_DIR)/_gitignore_global,$(HOME)/.gitignore_global); \
	fi
	@if [ -f $(HOME)/.gitconfig ] && ! grep -q "Git configuration template" $(HOME)/.gitconfig 2>/dev/null; then \
		printf "$(YELLOW}[warn]$(NC) ~/.gitconfig exists and isn't a dotfiles template. Skipping.\n"; \
	else \
		cp $(DOTFILES_DIR)/_gitconfig $(HOME)/.gitconfig; \
		printf "$(GREEN}[ok]$(NC) Git config installed\n"; \
	fi

utils:
	$(INFO) "Configuring Utilities..."
	$(call link_file,$(DOTFILES_DIR)/_bin,$(BIN_DIR))
	@chmod +x $(DOTFILES_DIR)/_bin/* 2>/dev/null || true

fonts:
	$(INFO) "Configuring Fonts..."
	@if [ -d "$(DOTFILES_DIR)/_fonts" ]; then \
		$(call link_file,$(DOTFILES_DIR)/_fonts,$(FONT_DIR)); \
		if command -v fc-cache >/dev/null 2>&1; then \
			fc-cache -f; \
			printf "$(GREEN}[ok]$(NC) Fonts installed and cache refreshed\n"; \
		fi \
	fi

inputrc:
	$(INFO) "Configuring Inputrc..."
	$(call link_file,$(DOTFILES_DIR)/_inputrc,$(HOME)/.inputrc)

clean: uninstall

uninstall:
	$(INFO) "Cleaning up dotfiles..."
	@sed -i '/# BEGIN DOTFILES/,/# END DOTFILES/d' $(HOME)/.bashrc 2>/dev/null || true
	@if [ -f $(HOME)/.gitconfig ] && grep -q "Git configuration template" $(HOME)/.gitconfig 2>/dev/null; then rm $(HOME)/.gitconfig; fi
	@rm -f $(HOME)/.dir_colors $(HOME)/.vimrc $(HOME)/.tmux.conf $(HOME)/.gitignore_global $(HOME)/.inputrc
	@rm -rf $(HOME)/.vim/colors $(NVIM_CONF) $(BIN_DIR) $(FONT_DIR)
	@printf "$(GREEN}[ok]$(NC) Cleanup complete\n"

status:
	@printf "$(BOLD)Dotfiles Status:$(NC)\n"
	@if grep -q "# BEGIN DOTFILES" $(HOME)/.bashrc 2>/dev/null; then printf "  $(GREEN)[installed]$(NC) Bash\n"; else printf "  $(RED)[missing]  $(NC) Bash\n"; fi
	@if [ -L $(HOME)/.vimrc ]; then printf "  $(GREEN)[installed]$(NC) Vim\n"; else printf "  $(RED)[missing]  $(NC) Vim\n"; fi
	@if [ -L $(NVIM_CONF) ]; then printf "  $(GREEN)[installed]$(NC) Neovim\n"; else printf "  $(RED)[missing]  $(NC) Neovim\n"; fi
	@if [ -L $(HOME)/.tmux.conf ]; then printf "  $(GREEN)[installed]$(NC) Tmux\n"; else printf "  $(RED)[missing]  $(NC) Tmux\n"; fi

update:
	git pull
	$(MAKE) sync
