#!/bin/bash
if [ $# -lt 2 ]; then
    echo "Usage: alarm_at HH:MM /path/to/music/folder"
    exit
fi
DESIRED=$((`date +%s -d "$1"`))
NOW=$((`date +%s`))
if [ $DESIRED -lt $NOW ]; then
    DESIRED=$((`date +%s -d "$1"` + 24*60*60))
fi
sudo killall rtcwake
#sudo rtcwake -l -m mem -t $DESIRED &
DIFERENCE=$(($DESIRED - $NOW))
echo $DIFERENCE
#sudo rtcwake -m disk -s $DIFERENCE &
sudo rtcwake -m mem -s $DIFERENCE &
echo "Suspending..."
sleep 2
xset dpms force on
clear
echo "Good morning!"
#mpg321 -Bz $2
mocp -S
mocp -o shuffle
mocp -cap $2
mocp 

