#!/bin/bash

if [  $# != 2 ] 
then 
	echo "Usage ex: $0 /dev/sdX /path/to/backup.img.gz"
	exit 1
fi 

SIZE=`/bin/df $1 | awk 'FNR==2{print $3}'`
# ex: dd if=/dev/sdX conv=sync,noerror bs=64K | gzip -c  > /path/to/backup.img.gz
dd if=$1 conv=sync,noerror bs=64K | pv -s ${SIZE}k | gzip -c  > $2
