#!/bin/sh

## define the font for dmenu to be used
DMENU_FN="Noto-11"
# DMENU_FN="Droid Sans-11"

## background colour for unselected menu-items
DMENU_NB="#2B2C2B"

## textcolour for unselected menu-items
#DMENU_NF="#F9FAF9"
DMENU_NF="#2E9EF4"
#DMENU_NF="#16A085"

## background colour for selected menu-items
DMENU_SB="#16A085"

## textcolour for selected menu-items
#DMENU_SF="#F9FAF9"
DMENU_SF="#2b2c2b"

## command for the terminal application to be used:
TERMINAL_CMD="terminal -e"

## export our variables
DMENU_OPTIONS="-b -fn $DMENU_FN -nb $DMENU_NB -nf $DMENU_NF -sf $DMENU_SF -sb $DMENU_SB"


exe=`dmenu_path | dmenu $DMENU_OPTIONS ${1+"$@"}` && exec $exe
