#!/bin/sh
# /usr/bin/i3exit

lock() {
	# blurlock
    import -window root /tmp/screenshot.png
    convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
    # convert /tmp/screenshot.png -spread 6 /tmp/screenshotblur.png
    rm /tmp/screenshot.png
    i3lock -f -i /tmp/screenshotblur.png -t
}

lock() {
    slock
}

stopTimeW(){
    ~/.bin/timew stop
}

stopTimeW

case "$1" in
    lock)
        # lock
        slock
        ;;
    logout)
        i3-msg exit
        ;;
    switch_user)
        dm-tool switch-to-greeter
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "== ! i3exit: missing or wrong argument ! ==
        Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0
