#!/bin/sh

idleAfter=600
notifyAfter=540

idle=false
tracking=false

timeWarrior() {
    # Check if Time Warrior is tracking
    if $(~/.bin/timew | grep -q "Tracking"); then
        traking=true
    else
        traking=false
    fi

    # Toggle timew when i3lock
    if [ "$(pgrep i3lock)" ]; then
        [ "$traking" = true ] && ~/.bin/timew stop
    else
        [ "$traking" = false ] && ~/.bin/timew continue
    fi
}

lock() {
    ~/.bin/i3exit lock
}

while true
do
    # Check if idle for longer than 10 min
    idleTimeSec=$(~/.bin/getidle)
    if [ $idleTimeSec -gt $idleAfter ] && [ $idle = false ] ; then
        # If Idle:
        # echo "Going Idle"
        lock
        idle=true
    elif [ $idleTimeSec -gt $notifyAfter ] && [ $idle = false ] ; then
        # echo "Going notify"
        notify-send -u critical -t 1000000 -- 'LOCKING screen in 60 seconds'
    fi

    if [ $idleTimeSec -lt $idleAfter ] && [ $idle = true ] ; then
        # If Not Idle:
        # echo "Going Idle"
        idle=false
    fi

    timeWarrior

    sleep 30
done

