#!/bin/bash

DIR="${HOME}/Desktop/screenshots"
DATE="$(date +%Y-%m-%d@%H%M%S)"
NAME="${DIR}/screenshot-${DATE}.png"
LOG="${DIR}/screenshots.log"

# Check if the dir to store the screenshots exists, else create it: 
if [ ! -d "${DIR}" ]; then mkdir -p "${DIR}"; fi 

# Screenshot a selected window
if [ "$1" = "win" ]; then scrot -s '%Y%m%d@%H%M%S_$wx$h.png' -e 'mv $f ~/Desktop/screenshots/'; fi

# Screenshot the entire screen
if [ "$1" = "scr" ]; then scrot '%Y%m%d@%H%M%S_$wx$h.png' -e 'mv $f ~/Desktop/screenshots/'; fi

# Screenshot a selected area
if [ "$1" = "area" ]; then scrot -s '%Y%m%d@%H%M%S_$wx$h.png' -e 'mv $f ~/Desktop/screenshots/'; fi

if [[ $# = 0 ]]; then
  # Display a warning if no area defined
  echo "No screenshot area has been specified. Screenshot not taken."
  echo "${DATE}: No screenshot area has been defined. Screenshot not taken." >> "${LOG}"
else
  # Save the screenshot in the directory and edit the log
  echo "${NAME}" >> "${LOG}"
  notify-send -u critical "${NAME}"
fi

##scrot '%Y%m%d@%H%M%S_$wx$h.png' -e 'mv $f ~/Desktop/screenshots/'

