#!/usr/bin/bash

inotifywait -m -e delete,create /run/media/jsilva/ | while read -r directory events filename;
do
	sleep 2
	#Show mounted usb drive devices
	for device in /sys/block/*
	do
		if udevadm info --query=property --path=$device | grep -q ^ID_BUS=usb
		then
			USBDISK=$(cat /proc/mounts | grep ${device##*/})
			DEV=$(echo $USBDISK | cut -f1 -d' ')
			NAME=$(echo $USBDISK | cut -f2 -d' ')
			echo -n "${DEV##*/} - ${NAME##*/}  "
		fi
	done
	#Show all mounted devices
	#for DISK in $(df -h | grep "/run/media/" | awk '{printf "%s ",$6}');
	#do
	#	echo -n "${DISK##*/} | ";
	#done
	echo
done
