#!/bin/bash

# Check if Time Warrior is tracking 
# if $(~/.bin/timew | grep -q "Tracking"); then 
#     status="$( ~/.bin/timew | while read a && read b && read c && read d; \
#     do echo \
#         $(echo $a | sed -e 's/ \+/-->/g')\;  \
#         $(echo $b | sed -e 's/ \+/-->/g')\;  \
#         $(echo $c | sed -e 's/ \+/-->/g')\;  \
#         $(echo $d | sed -e 's/ \+/-->/g') ;  \
#     done)"
# else 
#     status=$( ~/.bin/timew )
# fi

if $(timew | grep -q "Tracking"); then 
    status="[$(timew | head -n1)][This Week $(timew week | grep Tracked)][Today $(timew day | grep Tracked )]"
else 
    status=$(timew)
fi

echo ${status}



