#!/bin/bash

# export QEMU_AUDIO_DRV=pa

# qemu-system-x86_64 \
#     -m 2G \
#     -enable-kvm \
#     -usb \
#     -usbdevice tablet \
#     -net nic \
#     -net user \
#     -vga std \
#     -localtime \
#     -cpu host \
#     -smp cpus=2,maxcpus=4 \
#     -machine pc,accel=kvm \
#     -daemonize \
#     -drive file=/hd/Windows_7_64Bit_Feb2017.qcow2,if=virtio
#     # -drive file=/hd/Windows_7_64Bit_Feb2017.qcow2,format=qcow2,l2-cache-size=8M

vboxmanage startvm Win10CGI
