#!/bin/bash

URL=$1

youtube-dl --download-archive downloaded.txt \
    --no-post-overwrites \
    -ciwx --extract-audio \
    --audio-format mp3 \
    -o "%(title)s.%(ext)s" \
    --add-metadata $URL
