#!/bin/bash

URL=$1

youtube-dl --download-archive downloaded.txt \
    -i \
    --no-post-overwrites \
    -f bestaudio \
    --audio-quality 0 \
    -ciwx \
    --extract-audio \
    --audio-format mp3 \
    -o "%(title)s.%(ext)s" \
    --embed-thumbnail \
    --add-metadata $URL
