#!/usr/bin/env bash

# Bash only checks the first word of a command for an alias, any words after
# that are not checked. That means in a command like sudo ll, only the first word
# (sudo) is checked by bash for an alias, ll is ignored. We can tell bash to
# check the next word after the alias (i.e sudo) by adding a space to the end of
# the alias value.
alias sudo='sudo '
alias _="sudo"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.bash.d/dircolors && eval "$(dircolors -b ~/.bash.d/dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto --time-style=+"%d.%m.%Y %H:%M" -F'
    alias dir='dir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias l1='ls -1'
alias la='ls -A   --group-directories-first'
alias ll='ls -la  --group-directories-first'
alias l='ls -l   --group-directories-first'
alias llh='ls -h -la  --group-directories-first'
alias lh='ls -h -l   --group-directories-first'
alias l.='ls -ld  --group-directories-first .?*'
alias lt='ls -ltr'
alias lz='du -a -h -d1 | sort -h'


# Directory
alias rd='rmdir'

alias ..='cd ..'         # Go up one directory
alias ...='cd ../..'     # Go up two directories
alias ....='cd ../../..' # Go up three directories
alias -- -='cd -'        # Go back

alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

alias rm='trashit'
alias rrm='/bin/rm -rf'
alias emptybin='/bin/rm -rf ~/.Trash/*'
alias srm='sudo	/bin/rm -rf'
alias compact='_compactize'

alias vim="nvim"
alias vl="vim"
alias vi="vim -u ~/.vimrc_standalone"
alias vp="vim -u ~/.vimrc_plug"

alias printer='system-config-printer'
alias bacon='vi ~/.bash.d/'

alias errors='journalctl -p 3 -xb'

alias lsd='find . -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"'
alias lst='find . | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"'

alias ff="find . -type f -name "
alias fd="find . -type d -name "

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

#############
#  network  #
#############
alias fing="nmap -sP $(ip -4 -o addr show  | grep -oP '(?<=\b)192\.168\.[0-9]+\.(?=255)')* | grep report"

############
#  docker  #
############
alias drm="docker rm"
alias dps="docker ps"
alias dpa="docker ps -a"
alias di="docker images"  # List Docker images
alias dri="docker rmi -f"

# Get container IP
alias dip="docker inspect --format '{{ .NetworkSettings.IPAddress }}'"
# Run deamonized container, e.g., $dkd base /bin/echo hello
alias drd="docker run -d -P"
# Run interactive container, e.g., $dki base /bin/bash
alias drit="docker run -i -t -P"
# Execute interactive container, e.g., $dex base /bin/bash
alias dex="docker exec -i -t"
# Stop all containers
docker_stop_all() { docker stop $(docker ps -a -q); }
alias dsac="docker_stop_all"
# Remove all exited containers
docker_rm_exited() { docker rm $(docker ps -a -q -f status=exited); }
alias draec="docker_rm_exited"
# Remove all images
docker_rm_all_images() { docker rmi -f $(docker images -q); }
alias drai="docker_rm_all_images"
# Delete all dangling images (Untagged)
docker_rm_dangling_images() { docker rmi -f $(docker images -f "dangling=true" -q); }
alias drdi="docker_rm_dangling_images"
# Dockerfile build, e.g., $dbu tcnksm/test
dbu() { docker build -t=$1 .; }
# Bash into running container
dbash() { docker exec -it $(docker ps -aqf "name=$1") bash; }
# Show all alias related docker
dalias() { alias | grep 'docker' | sed "s/^\([^=]*\)=\(.*\)/\1 => \2/"| sed "s/['|\']//g" | sort; }


####################
#  Docker-compose  #
####################
alias dco="docker-compose"
alias dcor="docker-compose run"
alias dcob="docker-compose build"
alias dcofresh="docker-compose-fresh"
alias dcologs="docker-compose logs -f --tail 100"

##########
# pacman #
##########
alias pac='pacman -S'   # install
alias pacu='pacman -Syu'    # update, add 'a' to the list of letters to update AUR packages if you use yaourt
alias pacr='pacman -Rs'   # remove
alias pacs='pacman -Ss'      # search
alias paci='pacman -Si'      # info
alias paclo='pacman -Qdt'    # list orphans
alias pacro='paclo && sudo pacman -Rns $(pacman -Qtdq)' # remove orphans
alias pacc='pacman -Scc'    # clean cache
alias paclf='pacman -Ql'   # list files
palias() { alias | grep 'pacman' | sed "s/^\([^=]*\)=\(.*\)/\1 => \2/"| sed "s/['|\']//g" | sort; }

###########
#  eopkg  #
###########
alias solit="sudo eopkg install"
alias solri="sudo eopkg --reinstall"
alias solrm="sudo eopkg remove"
alias solup="sudo eopkg upgrade"
alias solsr="eopkg search"
alias solli="eopkg list-installed"
salias() { alias | grep 'eopkg' | sed "s/^\([^=]*\)=\(.*\)/\1 => \2/"| sed "s/['|\']//g" | sort; }

alias open='xdg-open'

# IP addresses
alias myip='curl ifconfig.me'

# List declared aliases, functions
alias listfunctions="declare -f | grep '^[a-z].* ()' | sed 's/{$//'" # show non _prefixed functions

#########
#  GIT  #
#########
alias gf='git fetch --all --prune'
alias gft='git fetch --all --prune --tags'
alias gfv='git fetch --all --prune --verbose'
alias gftv='git fetch --all --prune --tags --verbose'
alias gus='git reset HEAD'
alias gpristine='git reset --hard && git clean -dfx'
alias gclean='git clean -fd'
alias gg='git status'
alias ggs='git status -s'
alias gpl='git pull'
alias gpr='git pull --rebase'
alias gup='git fetch && git rebase'
alias gps='git push'
alias gr='git remote'
alias grv='git remote -v'
alias gra='git remote add'
alias gd='git diff | ydiff -s -w 0'
alias gdv='git diff -w "$@" | vim -R -'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gcm='git commit -v -m'
alias gci='git commit --interactive'
alias gb='git branch'
alias gbv='git branch -vv'
alias gbr='git branch -rvv'
alias gba='git branch -avv'
alias gbt='git branch --track'
alias gbm='git branch -m'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gcount='git shortlog -sn'
alias gco='git checkout'
alias gexport='git archive --format zip --output'
alias glog='git log'
alias gl='git log --graph --pretty=oneline --abbrev-commit'
alias gll="git log --graph --pretty=format:'%C(bold)%h%Creset%C(magenta)%d%Creset %s %C(yellow)<%an> %C(cyan)(%cr)%Creset' --abbrev-commit --date=relative"
alias gss="git show --stat"
alias gls="git show --name-only"
alias gld="git log -p -2 | ydiff -s -w 0"
alias gwc="git whatchanged"
# Show commits since last pull
alias gnew="git log HEAD@{1}..HEAD@{0}"
alias gsdiff='git show --name-only --oneline HEAD'
alias glsall='git ls-tree -r HEAD --name-only'
# Show all alias related docker
galias() { alias | grep 'git' | sed "s/^\([^=]*\)=\(.*\)/\1 => \2/"| sed "s/['|\']//g" | sort; }


