#!/usr/bin/env bash
# install.sh — link config components, or install vendored binaries, locally.
#
#   install.sh --configs [name ...]    no name = ALL_LOCAL
#   install.sh --bins    [name ...]    no name = every tool in vendor/linux-<arch>/
#
# A component is its LINKS entry in lib.sh (symlinked) plus an optional
# setup_<name> hook for what a symlink can't express. lazyvim is a clone, not
# a link set, so install_lazyvim replaces the generic path entirely.

set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

MODE=""; NAMES=()
while [ $# -gt 0 ]; do
    case "$1" in
        --configs) MODE=configs ;;
        --bins)    MODE=bins ;;
        -*)        die "Unknown option: $1" ;;
        *)         NAMES+=("$1") ;;
    esac
    shift
done
[ -n "$MODE" ] || die "usage: install.sh --configs|--bins [name ...]"

# ── Configs ──────────────────────────────────────────────────────────────────

# Symlink a repo file to its ~ target, backing up any real file in the way.
link_source() {
    local src="$DOTFILES/$1" target dest
    target=$(target_of "$1"); dest=$(local_path "$target")
    [ -e "$src" ] || { warn "$1 is not in the repo — check LINKS in scripts/lib.sh"; return 1; }
    if [ -L "$dest" ]; then
        rm "$dest"
    elif [ -e "$dest" ]; then
        local bak; bak="$dest.backup.$(date +%Y%m%d_%H%M%S)"
        warn "backing up $target → $bak"
        mv "$dest" "$bak"
    fi
    mkdir -p "$(dirname "$dest")"
    ln -s "$src" "$dest"
    ok "$target"
}

install_component() {
    local comp=$1 src
    info "$comp"
    if declare -f "install_$comp" >/dev/null; then "install_$comp"; return; fi
    while read -r src; do [ -n "$src" ] && link_source "$src"; done < <(sources_of "$comp")
    if declare -f "setup_$comp" >/dev/null; then "setup_$comp"; fi
}

setup_bash() {
    run_on_target "$BASH_WIRE" && ok "wired into ~/.bashrc"
    if [ ! -f "$HOME/.bashrc.local" ]; then
        printf '# Local machine-specific overrides\n# This file is ignored by git\n' > "$HOME/.bashrc.local"
        ok "created ~/.bashrc.local"
    fi
}

setup_git() {
    # If an older install symlinked ~/.gitconfig into the repo, de-link it so
    # 'git config --global' below can't write through into the repo file.
    if ours "$HOME/.gitconfig"; then rm "$HOME/.gitconfig"; fi
    run_on_target "p=\"$DOTFILES/git/dot-gitconfig\"" "$GIT_WIRE" && ok "included from ~/.gitconfig"
}

setup_vim() { mkdir -p "$DOTFILES"/vim/dot-vim/{undo,backup,swap}; }

setup_utils() { chmod +x "$DOTFILES"/utils/dot-local/bin/*; }

setup_aerc() {
    [ -f "$CONFIG_HOME/aerc/accounts.conf" ] \
        || warn "no $CONFIG_HOME/aerc/accounts.conf — aerc has no accounts until you add one"
}

# joshuto reads [display] mode once at startup and has no runtime toggle, so
# the dual-pane layout needs a config dir of its own. Only joshuto.toml
# differs, and it is GENERATED from the real one with the mode line swapped —
# so the two can never drift — while the other files link back to the
# originals (joshuto replaces each config file wholesale, never merges).
# Launched by the `jjs` wrapper in bash/dot-bashrc_ext.
setup_joshuto() {
    local src="$DOTFILES/joshuto/dot-config/joshuto" dest="$CONFIG_HOME/joshuto-hsplit" f
    mkdir -p "$dest"
    {
        printf '# GENERATED by scripts/install.sh — edit joshuto/dot-config/joshuto/joshuto.toml.\n'
        sed 's/^mode = "default"$/mode = "hsplit"/' "$src/joshuto.toml"
    } > "$dest/joshuto.toml"
    grep -q '^mode = "hsplit"$' "$dest/joshuto.toml" \
        && ok "~/.config/joshuto-hsplit/joshuto.toml" \
        || warn "no 'mode = \"default\"' line in joshuto.toml — jjs will not be dual-pane"
    for f in keymap.toml mimetype.toml preview_file.sh; do
        ln -sfn "$src/$f" "$dest/$f"
    done
}

# Under WSL the terminal drawing your text is a WINDOWS application and can
# only use fonts installed on the Windows side — it cannot see the Linux
# ~/.local/share/fonts just linked, so glyphs render as tofu. Registering a
# font from WSL means writing the Windows registry, so stage the files where
# Explorer can reach them and print the two steps left. No-op outside WSL.
setup_fonts() {
    command -v fc-cache >/dev/null && fc-cache -f && ok "font cache refreshed"
    grep -qi microsoft /proc/version 2>/dev/null || return 0
    local win_user dest
    win_user=$(cmd.exe /c 'echo %USERNAME%' 2>/dev/null | tr -d '\r\n')
    if [ -z "$win_user" ] || [ ! -d "/mnt/c/Users/$win_user" ]; then
        warn "WSL, but the Windows user can't be resolved — install the Nerd Font by hand"
        warn "from fonts/dot-local/share/fonts/UbuntuMono/"
        return 0
    fi
    dest="/mnt/c/Users/$win_user/Downloads/nerd-fonts"
    mkdir -p "$dest" 2>/dev/null || { warn "cannot write $dest — skipping Windows staging"; return 0; }
    cp "$DOTFILES"/fonts/dot-local/share/fonts/UbuntuMono/UbuntuMonoNerdFontMono-*.ttf "$dest"/ 2>/dev/null
    ok "staged Nerd Font → $dest"
    printf "  ${BOLD}Two steps left, on the Windows side (once per machine):${NC}\n"
    printf "    1. Open that folder, select the .ttf files, right-click → Install\n"
    printf "    2. Terminal → Settings → profile → Appearance → Font face: ${BOLD}UbuntuMono Nerd Font Mono${NC}\n"
}

# LazyVim is not a stowed dotfile — it's an upstream starter template that
# lazy.nvim then self-manages (its own lockfile, its own plugin updates).
# NVIM_APPNAME isolates it in ~/.config/lazyvim, entirely separate from the
# nvim component, so the two can't collide. Opt-in only (not in ALL_LOCAL): it
# needs network + git on first run, and re-running this must NOT clobber your
# in-editor plugin changes, so an existing clone is left untouched.
install_lazyvim() {
    local dest="$CONFIG_HOME/lazyvim" f
    if [ -d "$dest" ]; then
        ok "$dest already present — left untouched"
    else
        command -v git >/dev/null || { warn "git not found — cannot clone the LazyVim starter"; return 0; }
        git clone --depth=1 https://github.com/LazyVim/starter "$dest" \
            && rm -rf "$dest/.git" && ok "cloned LazyVim starter → $dest  (launch with: lvim)"
    fi
    # Re-linked every run so overlay changes reach an existing clone. Every
    # *.lua in nvim/lazyvim-plugins/ becomes a lua/plugins/ override — add a
    # file there and it's picked up with no script change.
    [ -d "$dest/lua/plugins" ] || return 0
    for f in "$DOTFILES"/nvim/lazyvim-plugins/*.lua; do
        [ -f "$f" ] || continue
        ln -sfn "$f" "$dest/lua/plugins/$(basename "$f")"
        ok "lazyvim/lua/plugins/$(basename "$f")"
    done
}

# ── Binaries ─────────────────────────────────────────────────────────────────
# Copied, not linked, so 'make clean' can wipe vendor/ without breaking them.

install_bin() {
    local tool=$1; local src="$VENDOR_DIR/$tool"
    info "$tool"
    vendored "$tool" || { warn "not in vendor/linux-$ARCH/ — run 'make vendor $tool'"; return; }
    mkdir -p "$HOME/.local/bin"
    cp "$src" "$HOME/.local/bin/$tool" && chmod +x "$HOME/.local/bin/$tool"
    ok "~/.local/bin/$tool"
    [ "$tool" = nvim ] || return 0
    # Resolved relative to the binary's prefix (~/.local/): share/nvim/runtime
    # is VIMRUNTIME, lib/nvim/parser holds the treesitter grammars that must
    # match the bundled queries.
    rm -rf "$HOME/.local/share/nvim/runtime" "$HOME/.local/lib/nvim/parser"
    mkdir -p "$HOME/.local/share/nvim" "$HOME/.local/lib/nvim"
    cp -r "$VENDOR_DIR/nvim-runtime" "$HOME/.local/share/nvim/runtime" && ok "~/.local/share/nvim/runtime"
    cp -r "$VENDOR_DIR/nvim-parsers" "$HOME/.local/lib/nvim/parser"    && ok "~/.local/lib/nvim/parser"
}

# ── Drive it ─────────────────────────────────────────────────────────────────

if [ "$MODE" = configs ]; then
    [ ${#NAMES[@]} -gt 0 ] || NAMES=("${ALL_LOCAL[@]}")
    for n in "${NAMES[@]}"; do
        is_component "$n" || die "Unknown component '$n'. Available: $COMPONENTS"
    done
    for n in "${NAMES[@]}"; do install_component "$n"; done
else
    if [ ${#NAMES[@]} -eq 0 ]; then
        for t in "${TOOL_NAMES[@]}"; do vendored "$t" && NAMES+=("$t"); done
        [ ${#NAMES[@]} -gt 0 ] || die "nothing in vendor/linux-$ARCH/ — run 'make vendor' first"
    fi
    for n in "${NAMES[@]}"; do
        is_tool "$n" || die "Unknown tool '$n'. Available: ${TOOL_NAMES[*]}"
    done
    for n in "${NAMES[@]}"; do install_bin "$n"; done
    warn "run 'hash -r' (or open a new terminal) so the shell picks up the new binaries"
fi

printf "\n${GREEN}Done!${NC}\n"
